### ISSUE TITLE
Could you tag the latest version?

### ISSUE THREAD

**Issue by paluh** [Risto-Stevcev/purescript-exitcodes#2]
Your latest release (2.0.0) doesn't contain last commit and it has old dependency list - I'm not able to easily use it with purescript-0.11.

**Comment by Risto-Stevcev** [comment]
Hi Paluh
Sorry about that, I saw your ticket initially and then got sidetracked and forgot all about this. I'm adding @safareli as a maintainer, he'll bump the version for 0.12

**Comment by safareli** [comment]
https://github.com/Risto-Stevcev/purescript-exitcodes/releases/tag/v4.0.0
