### ISSUE TITLE
Add exitcodes to packages set

### ISSUE THREAD

**Issue by srghma** [Risto-Stevcev/purescript-exitcodes#6]
# Actual:

```
$ spago install
spago: Package `exitcodes` does not exist in package set
```

# Temp fix:

in `packages.dhall`

```
let additions =
{ exitcodes =
  mkPackage
    [ "enums"
    ]
    "https://github.com/Risto-Stevcev/purescript-exitcodes"
    "master"
}

in  upstream // overrides // additions

**Comment by Risto-Stevcev** [comment]
Hi @srghma  ,

Thanks for the PR, and sorry for any inconvenience my delay in communication may have caused. I'm no longer maintaining my Purescript repositories, I've been meaning to archive them. Feel free to fork the repo.

Risto
